version: '3.8'

services:
  db_dev:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: devdb
    ports:
      - "5433:5432"
    volumes:
      - db_dev_data:/var/lib/postgresql/data

  db_test:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: testdb
    ports:
      - "5434:5432"
    volumes:
      - db_test_data:/var/lib/postgresql/data

volumes:
  db_dev_data:
  db_test_data:
